release:
  prerelease: auto
  draft: true
  name_template: '{{.ProjectName}} {{.Version}}'

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

gomod:
  proxy: true

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{.CommitTimestamp}}'
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/mzbaulhaque/gois/internal/build.ProjectName={{.ProjectName}}
      - -X github.com/mzbaulhaque/gois/internal/build.Version={{.Version}}

archives:
  - name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      amd64: x86_64
      darwin: macOS
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: '{{.ProjectName}}_checksums.txt'

snapshot:
  name_template: "{{.Tag}}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^chore'
      - '^refactor'
      - '^style'
      - '^test'
      - '^Update$'
      - Merge pull request
