go:
  version: 1.16
repository:
  path: github.com/mzbaulhaque/gomage
build:
  binaries:
    - name: gomage
      path: ./cmd/gomage
  flags: -a -tags netgo
  ldflags: |
    -X {{repoPath}}/main.programVersion={{.Version}}
    -X {{repoPath}}/main.buildNumber={{.Revision}}
tarball:
  prefix: .
  files:
    - CHANGELOG.md
    - LICENSE
crossbuild:
  platforms:
    - linux/amd64
    - darwin/amd64
    - windows/amd64
