dist: bionic

language: go

go:
  - 1.16.x

git:
  depth: 1

notifications:
  email: false

jobs:
  include:
    - stage: test
      script:
        - make check
        - go mod verify
        - make test
        - if [ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]; then bash <(curl -s https://codecov.io/bash); fi
#    - stage: build
#      if: tag IS present
#      script:
#        - make build
