name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Set tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Make release assets
        run: VERSION=${{ steps.vars.outputs.tag }} make release
      - name: Create release
        run: GH_ACCESS_TOKEN=${{ secrets.GH_ACCESS_TOKEN }} bash scripts/gh-release.sh ${{ steps.vars.outputs.tag }}
