name: Test pull requests against develop or master

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Run checks
        run: make check
      - name: Run tests
        run: make test
      - name: Build
        run: make build
